# Generated by Django 2.2.9 on 2020-01-13 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Primitive', 'Primitive'), ('CORPSE', 'CORPSE'), ('GAUSSIAN', 'Gaussian'), ('CinBB', 'CinBB'), ('CinSK', 'CinSK')], max_length=9)),
                ('max_rabi_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('polar_angle', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
