version: "3.5"


services:
#  app:
#    build: .
#    container_name: qctrl_app
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: ${DB_NAME:-app}
#      DB_USER: ${DB_USER:-postgres}
#      DB_PASSWORD: ${DB_PASS:-password}
#    volumes:
#      - ./app:/app
#    networks:
#      - qctrl_app
#    depends_on:
#      - postgres
#    command: python manage.py runserver
##      - sh -c "python manage.py runserver 0.0.0.0:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./.pgadmin:/root/.pgadmin
    ports:
      - "15050:80"
    networks:
      - qctrl_app
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:12.1-alpine
    container_name: postgres_local
    environment:
      POSTGRES_DB: ${DB_NAME:-app}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      PGDATA: /data/postgres
    volumes:
      - ./.postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - qctrl_app
    restart: unless-stopped


networks:
  qctrl_app:
    driver: bridge

#    volumes:
##    -