# Created by: Aymen Al-Quaiti
# For QCTRL Backend Challenge
# January  2020
"""
Auto-generated by Django. Can be used to integrate app with admin site
"""


from django.contrib import admin

# Register your models here.
