# Created by: Aymen Al-Quaiti
# For QCTRL Backend Challenge
# January  2020
"""
Auto-generated by Django. Configures App
"""

from django.apps import AppConfig


class AppConfig(AppConfig):
    name = 'control'
